# change appropriately
# jbr_win = C:/jbrt/jbr
jbr_mac = /Users/vladimir.kharitonov/Library/Java/JavaVirtualMachines/jbr-25.0.2/Contents/Home
# jbr_linux = /home/tav/jbrt/jbr

# Path to be passed to tests as -Djcef.native.bundle.path=...
# TODO: point to the bundle in the build dir(change build scripts)
# jcef_native_bundle_path = /Users/vladimir.kharitonov/develop/jcef/native_bundle/jcef