/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.jetbrains.cef.remote.thrift_codegen;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class AcceleratedPaintInfo implements com.jetbrains.cef.remote.thrift.TBase<AcceleratedPaintInfo, AcceleratedPaintInfo._Fields>, java.io.Serializable, Cloneable, Comparable<AcceleratedPaintInfo> {
  private static final com.jetbrains.cef.remote.thrift.protocol.TStruct STRUCT_DESC = new com.jetbrains.cef.remote.thrift.protocol.TStruct("AcceleratedPaintInfo");

  private static final com.jetbrains.cef.remote.thrift.protocol.TField FORMAT_FIELD_DESC = new com.jetbrains.cef.remote.thrift.protocol.TField("format", com.jetbrains.cef.remote.thrift.protocol.TType.I32, (short)1);
  private static final com.jetbrains.cef.remote.thrift.protocol.TField HANDLE_FIELD_DESC = new com.jetbrains.cef.remote.thrift.protocol.TField("handle", com.jetbrains.cef.remote.thrift.protocol.TType.I64, (short)2);
  private static final com.jetbrains.cef.remote.thrift.protocol.TField CODED_SIZE_FIELD_DESC = new com.jetbrains.cef.remote.thrift.protocol.TField("coded_size", com.jetbrains.cef.remote.thrift.protocol.TType.STRUCT, (short)3);

  private static final com.jetbrains.cef.remote.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new AcceleratedPaintInfoStandardSchemeFactory();
  private static final com.jetbrains.cef.remote.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new AcceleratedPaintInfoTupleSchemeFactory();

  /**
   * 
   * @see AcceleratedPaintInfoColorType
   */
  public @com.jetbrains.cef.remote.thrift.annotation.Nullable AcceleratedPaintInfoColorType format; // required
  public long handle; // required
  public @com.jetbrains.cef.remote.thrift.annotation.Nullable com.jetbrains.cef.remote.thrift_codegen.Size coded_size; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements com.jetbrains.cef.remote.thrift.TFieldIdEnum {
    /**
     * 
     * @see AcceleratedPaintInfoColorType
     */
    FORMAT((short)1, "format"),
    HANDLE((short)2, "handle"),
    CODED_SIZE((short)3, "coded_size");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @com.jetbrains.cef.remote.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FORMAT
          return FORMAT;
        case 2: // HANDLE
          return HANDLE;
        case 3: // CODED_SIZE
          return CODED_SIZE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @com.jetbrains.cef.remote.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __HANDLE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FORMAT, new com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData("format", com.jetbrains.cef.remote.thrift.TFieldRequirementType.REQUIRED, 
        new com.jetbrains.cef.remote.thrift.meta_data.EnumMetaData(com.jetbrains.cef.remote.thrift.protocol.TType.ENUM, AcceleratedPaintInfoColorType.class)));
    tmpMap.put(_Fields.HANDLE, new com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData("handle", com.jetbrains.cef.remote.thrift.TFieldRequirementType.REQUIRED, 
        new com.jetbrains.cef.remote.thrift.meta_data.FieldValueMetaData(com.jetbrains.cef.remote.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.CODED_SIZE, new com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData("coded_size", com.jetbrains.cef.remote.thrift.TFieldRequirementType.REQUIRED, 
        new com.jetbrains.cef.remote.thrift.meta_data.StructMetaData(com.jetbrains.cef.remote.thrift.protocol.TType.STRUCT, com.jetbrains.cef.remote.thrift_codegen.Size.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AcceleratedPaintInfo.class, metaDataMap);
  }

  public AcceleratedPaintInfo() {
  }

  public AcceleratedPaintInfo(
    AcceleratedPaintInfoColorType format,
    long handle,
    com.jetbrains.cef.remote.thrift_codegen.Size coded_size)
  {
    this();
    this.format = format;
    this.handle = handle;
    setHandleIsSet(true);
    this.coded_size = coded_size;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AcceleratedPaintInfo(AcceleratedPaintInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetFormat()) {
      this.format = other.format;
    }
    this.handle = other.handle;
    if (other.isSetCoded_size()) {
      this.coded_size = new com.jetbrains.cef.remote.thrift_codegen.Size(other.coded_size);
    }
  }

  @Override
  public AcceleratedPaintInfo deepCopy() {
    return new AcceleratedPaintInfo(this);
  }

  @Override
  public void clear() {
    this.format = null;
    setHandleIsSet(false);
    this.handle = 0;
    this.coded_size = null;
  }

  /**
   * 
   * @see AcceleratedPaintInfoColorType
   */
  @com.jetbrains.cef.remote.thrift.annotation.Nullable
  public AcceleratedPaintInfoColorType getFormat() {
    return this.format;
  }

  /**
   * 
   * @see AcceleratedPaintInfoColorType
   */
  public AcceleratedPaintInfo setFormat(@com.jetbrains.cef.remote.thrift.annotation.Nullable AcceleratedPaintInfoColorType format) {
    this.format = format;
    return this;
  }

  public void unsetFormat() {
    this.format = null;
  }

  /** Returns true if field format is set (has been assigned a value) and false otherwise */
  public boolean isSetFormat() {
    return this.format != null;
  }

  public void setFormatIsSet(boolean value) {
    if (!value) {
      this.format = null;
    }
  }

  public long getHandle() {
    return this.handle;
  }

  public AcceleratedPaintInfo setHandle(long handle) {
    this.handle = handle;
    setHandleIsSet(true);
    return this;
  }

  public void unsetHandle() {
    __isset_bitfield = com.jetbrains.cef.remote.thrift.EncodingUtils.clearBit(__isset_bitfield, __HANDLE_ISSET_ID);
  }

  /** Returns true if field handle is set (has been assigned a value) and false otherwise */
  public boolean isSetHandle() {
    return com.jetbrains.cef.remote.thrift.EncodingUtils.testBit(__isset_bitfield, __HANDLE_ISSET_ID);
  }

  public void setHandleIsSet(boolean value) {
    __isset_bitfield = com.jetbrains.cef.remote.thrift.EncodingUtils.setBit(__isset_bitfield, __HANDLE_ISSET_ID, value);
  }

  @com.jetbrains.cef.remote.thrift.annotation.Nullable
  public com.jetbrains.cef.remote.thrift_codegen.Size getCoded_size() {
    return this.coded_size;
  }

  public AcceleratedPaintInfo setCoded_size(@com.jetbrains.cef.remote.thrift.annotation.Nullable com.jetbrains.cef.remote.thrift_codegen.Size coded_size) {
    this.coded_size = coded_size;
    return this;
  }

  public void unsetCoded_size() {
    this.coded_size = null;
  }

  /** Returns true if field coded_size is set (has been assigned a value) and false otherwise */
  public boolean isSetCoded_size() {
    return this.coded_size != null;
  }

  public void setCoded_sizeIsSet(boolean value) {
    if (!value) {
      this.coded_size = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @com.jetbrains.cef.remote.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case FORMAT:
      if (value == null) {
        unsetFormat();
      } else {
        setFormat((AcceleratedPaintInfoColorType)value);
      }
      break;

    case HANDLE:
      if (value == null) {
        unsetHandle();
      } else {
        setHandle((java.lang.Long)value);
      }
      break;

    case CODED_SIZE:
      if (value == null) {
        unsetCoded_size();
      } else {
        setCoded_size((com.jetbrains.cef.remote.thrift_codegen.Size)value);
      }
      break;

    }
  }

  @com.jetbrains.cef.remote.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case FORMAT:
      return getFormat();

    case HANDLE:
      return getHandle();

    case CODED_SIZE:
      return getCoded_size();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case FORMAT:
      return isSetFormat();
    case HANDLE:
      return isSetHandle();
    case CODED_SIZE:
      return isSetCoded_size();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof AcceleratedPaintInfo)
      return this.equals((AcceleratedPaintInfo)that);
    return false;
  }

  public boolean equals(AcceleratedPaintInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_format = true && this.isSetFormat();
    boolean that_present_format = true && that.isSetFormat();
    if (this_present_format || that_present_format) {
      if (!(this_present_format && that_present_format))
        return false;
      if (!this.format.equals(that.format))
        return false;
    }

    boolean this_present_handle = true;
    boolean that_present_handle = true;
    if (this_present_handle || that_present_handle) {
      if (!(this_present_handle && that_present_handle))
        return false;
      if (this.handle != that.handle)
        return false;
    }

    boolean this_present_coded_size = true && this.isSetCoded_size();
    boolean that_present_coded_size = true && that.isSetCoded_size();
    if (this_present_coded_size || that_present_coded_size) {
      if (!(this_present_coded_size && that_present_coded_size))
        return false;
      if (!this.coded_size.equals(that.coded_size))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetFormat()) ? 131071 : 524287);
    if (isSetFormat())
      hashCode = hashCode * 8191 + format.getValue();

    hashCode = hashCode * 8191 + com.jetbrains.cef.remote.thrift.TBaseHelper.hashCode(handle);

    hashCode = hashCode * 8191 + ((isSetCoded_size()) ? 131071 : 524287);
    if (isSetCoded_size())
      hashCode = hashCode * 8191 + coded_size.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(AcceleratedPaintInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetFormat(), other.isSetFormat());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFormat()) {
      lastComparison = com.jetbrains.cef.remote.thrift.TBaseHelper.compareTo(this.format, other.format);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetHandle(), other.isSetHandle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHandle()) {
      lastComparison = com.jetbrains.cef.remote.thrift.TBaseHelper.compareTo(this.handle, other.handle);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCoded_size(), other.isSetCoded_size());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCoded_size()) {
      lastComparison = com.jetbrains.cef.remote.thrift.TBaseHelper.compareTo(this.coded_size, other.coded_size);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @com.jetbrains.cef.remote.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(com.jetbrains.cef.remote.thrift.protocol.TProtocol iprot) throws com.jetbrains.cef.remote.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(com.jetbrains.cef.remote.thrift.protocol.TProtocol oprot) throws com.jetbrains.cef.remote.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("AcceleratedPaintInfo(");
    boolean first = true;

    sb.append("format:");
    if (this.format == null) {
      sb.append("null");
    } else {
      sb.append(this.format);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("handle:");
    sb.append(this.handle);
    first = false;
    if (!first) sb.append(", ");
    sb.append("coded_size:");
    if (this.coded_size == null) {
      sb.append("null");
    } else {
      sb.append(this.coded_size);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws com.jetbrains.cef.remote.thrift.TException {
    // check for required fields
    if (format == null) {
      throw new com.jetbrains.cef.remote.thrift.protocol.TProtocolException("Required field 'format' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'handle' because it's a primitive and you chose the non-beans generator.
    if (coded_size == null) {
      throw new com.jetbrains.cef.remote.thrift.protocol.TProtocolException("Required field 'coded_size' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (coded_size != null) {
      coded_size.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new com.jetbrains.cef.remote.thrift.protocol.TCompactProtocol(new com.jetbrains.cef.remote.thrift.transport.TIOStreamTransport(out)));
    } catch (com.jetbrains.cef.remote.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new com.jetbrains.cef.remote.thrift.protocol.TCompactProtocol(new com.jetbrains.cef.remote.thrift.transport.TIOStreamTransport(in)));
    } catch (com.jetbrains.cef.remote.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AcceleratedPaintInfoStandardSchemeFactory implements com.jetbrains.cef.remote.thrift.scheme.SchemeFactory {
    @Override
    public AcceleratedPaintInfoStandardScheme getScheme() {
      return new AcceleratedPaintInfoStandardScheme();
    }
  }

  private static class AcceleratedPaintInfoStandardScheme extends com.jetbrains.cef.remote.thrift.scheme.StandardScheme<AcceleratedPaintInfo> {

    @Override
    public void read(com.jetbrains.cef.remote.thrift.protocol.TProtocol iprot, AcceleratedPaintInfo struct) throws com.jetbrains.cef.remote.thrift.TException {
      com.jetbrains.cef.remote.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == com.jetbrains.cef.remote.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FORMAT
            if (schemeField.type == com.jetbrains.cef.remote.thrift.protocol.TType.I32) {
              struct.format = com.jetbrains.cef.remote.thrift_codegen.AcceleratedPaintInfoColorType.findByValue(iprot.readI32());
              struct.setFormatIsSet(true);
            } else { 
              com.jetbrains.cef.remote.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // HANDLE
            if (schemeField.type == com.jetbrains.cef.remote.thrift.protocol.TType.I64) {
              struct.handle = iprot.readI64();
              struct.setHandleIsSet(true);
            } else { 
              com.jetbrains.cef.remote.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CODED_SIZE
            if (schemeField.type == com.jetbrains.cef.remote.thrift.protocol.TType.STRUCT) {
              struct.coded_size = new com.jetbrains.cef.remote.thrift_codegen.Size();
              struct.coded_size.read(iprot);
              struct.setCoded_sizeIsSet(true);
            } else { 
              com.jetbrains.cef.remote.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            com.jetbrains.cef.remote.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetHandle()) {
        throw new com.jetbrains.cef.remote.thrift.protocol.TProtocolException("Required field 'handle' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(com.jetbrains.cef.remote.thrift.protocol.TProtocol oprot, AcceleratedPaintInfo struct) throws com.jetbrains.cef.remote.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.format != null) {
        oprot.writeFieldBegin(FORMAT_FIELD_DESC);
        oprot.writeI32(struct.format.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(HANDLE_FIELD_DESC);
      oprot.writeI64(struct.handle);
      oprot.writeFieldEnd();
      if (struct.coded_size != null) {
        oprot.writeFieldBegin(CODED_SIZE_FIELD_DESC);
        struct.coded_size.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AcceleratedPaintInfoTupleSchemeFactory implements com.jetbrains.cef.remote.thrift.scheme.SchemeFactory {
    @Override
    public AcceleratedPaintInfoTupleScheme getScheme() {
      return new AcceleratedPaintInfoTupleScheme();
    }
  }

  private static class AcceleratedPaintInfoTupleScheme extends com.jetbrains.cef.remote.thrift.scheme.TupleScheme<AcceleratedPaintInfo> {

    @Override
    public void write(com.jetbrains.cef.remote.thrift.protocol.TProtocol prot, AcceleratedPaintInfo struct) throws com.jetbrains.cef.remote.thrift.TException {
      com.jetbrains.cef.remote.thrift.protocol.TTupleProtocol oprot = (com.jetbrains.cef.remote.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.format.getValue());
      oprot.writeI64(struct.handle);
      struct.coded_size.write(oprot);
    }

    @Override
    public void read(com.jetbrains.cef.remote.thrift.protocol.TProtocol prot, AcceleratedPaintInfo struct) throws com.jetbrains.cef.remote.thrift.TException {
      com.jetbrains.cef.remote.thrift.protocol.TTupleProtocol iprot = (com.jetbrains.cef.remote.thrift.protocol.TTupleProtocol) prot;
      struct.format = com.jetbrains.cef.remote.thrift_codegen.AcceleratedPaintInfoColorType.findByValue(iprot.readI32());
      struct.setFormatIsSet(true);
      struct.handle = iprot.readI64();
      struct.setHandleIsSet(true);
      struct.coded_size = new com.jetbrains.cef.remote.thrift_codegen.Size();
      struct.coded_size.read(iprot);
      struct.setCoded_sizeIsSet(true);
    }
  }

  private static <S extends com.jetbrains.cef.remote.thrift.scheme.IScheme> S scheme(com.jetbrains.cef.remote.thrift.protocol.TProtocol proto) {
    return (com.jetbrains.cef.remote.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

