/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.jetbrains.cef.remote.thrift_codegen;


public enum CefValueType implements com.jetbrains.cef.remote.thrift.TEnum {
  BOOL(0),
  INT(1),
  DOUBLE(2),
  STRING(3),
  BYTE_BUFFER(4),
  MAP(5),
  LIST(6),
  NONE(7);

  private final int value;

  private CefValueType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @com.jetbrains.cef.remote.thrift.annotation.Nullable
  public static CefValueType findByValue(int value) { 
    switch (value) {
      case 0:
        return BOOL;
      case 1:
        return INT;
      case 2:
        return DOUBLE;
      case 3:
        return STRING;
      case 4:
        return BYTE_BUFFER;
      case 5:
        return MAP;
      case 6:
        return LIST;
      case 7:
        return NONE;
      default:
        return null;
    }
  }
}
