/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.jetbrains.cef.remote.thrift_codegen;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class CefValue implements com.jetbrains.cef.remote.thrift.TBase<CefValue, CefValue._Fields>, java.io.Serializable, Cloneable, Comparable<CefValue> {
  private static final com.jetbrains.cef.remote.thrift.protocol.TStruct STRUCT_DESC = new com.jetbrains.cef.remote.thrift.protocol.TStruct("CefValue");

  private static final com.jetbrains.cef.remote.thrift.protocol.TField TYPE_FIELD_DESC = new com.jetbrains.cef.remote.thrift.protocol.TField("type", com.jetbrains.cef.remote.thrift.protocol.TType.I32, (short)1);
  private static final com.jetbrains.cef.remote.thrift.protocol.TField INT_VAL_FIELD_DESC = new com.jetbrains.cef.remote.thrift.protocol.TField("intVal", com.jetbrains.cef.remote.thrift.protocol.TType.I64, (short)2);
  private static final com.jetbrains.cef.remote.thrift.protocol.TField DOUBLE_VAL_FIELD_DESC = new com.jetbrains.cef.remote.thrift.protocol.TField("doubleVal", com.jetbrains.cef.remote.thrift.protocol.TType.DOUBLE, (short)3);
  private static final com.jetbrains.cef.remote.thrift.protocol.TField STR_VAL_FIELD_DESC = new com.jetbrains.cef.remote.thrift.protocol.TField("strVal", com.jetbrains.cef.remote.thrift.protocol.TType.STRING, (short)4);
  private static final com.jetbrains.cef.remote.thrift.protocol.TField BIN_VAL_FIELD_DESC = new com.jetbrains.cef.remote.thrift.protocol.TField("binVal", com.jetbrains.cef.remote.thrift.protocol.TType.STRING, (short)5);
  private static final com.jetbrains.cef.remote.thrift.protocol.TField MAP_VAL_FIELD_DESC = new com.jetbrains.cef.remote.thrift.protocol.TField("mapVal", com.jetbrains.cef.remote.thrift.protocol.TType.MAP, (short)6);
  private static final com.jetbrains.cef.remote.thrift.protocol.TField LIST_VAL_FIELD_DESC = new com.jetbrains.cef.remote.thrift.protocol.TField("listVal", com.jetbrains.cef.remote.thrift.protocol.TType.LIST, (short)7);

  private static final com.jetbrains.cef.remote.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CefValueStandardSchemeFactory();
  private static final com.jetbrains.cef.remote.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CefValueTupleSchemeFactory();

  /**
   * 
   * @see CefValueType
   */
  public @com.jetbrains.cef.remote.thrift.annotation.Nullable CefValueType type; // required
  public long intVal; // optional
  public double doubleVal; // optional
  public @com.jetbrains.cef.remote.thrift.annotation.Nullable java.lang.String strVal; // optional
  public @com.jetbrains.cef.remote.thrift.annotation.Nullable java.nio.ByteBuffer binVal; // optional
  public @com.jetbrains.cef.remote.thrift.annotation.Nullable java.util.Map<java.lang.String,CefValue> mapVal; // optional
  public @com.jetbrains.cef.remote.thrift.annotation.Nullable java.util.List<CefValue> listVal; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements com.jetbrains.cef.remote.thrift.TFieldIdEnum {
    /**
     * 
     * @see CefValueType
     */
    TYPE((short)1, "type"),
    INT_VAL((short)2, "intVal"),
    DOUBLE_VAL((short)3, "doubleVal"),
    STR_VAL((short)4, "strVal"),
    BIN_VAL((short)5, "binVal"),
    MAP_VAL((short)6, "mapVal"),
    LIST_VAL((short)7, "listVal");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @com.jetbrains.cef.remote.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TYPE
          return TYPE;
        case 2: // INT_VAL
          return INT_VAL;
        case 3: // DOUBLE_VAL
          return DOUBLE_VAL;
        case 4: // STR_VAL
          return STR_VAL;
        case 5: // BIN_VAL
          return BIN_VAL;
        case 6: // MAP_VAL
          return MAP_VAL;
        case 7: // LIST_VAL
          return LIST_VAL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @com.jetbrains.cef.remote.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __INTVAL_ISSET_ID = 0;
  private static final int __DOUBLEVAL_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.INT_VAL,_Fields.DOUBLE_VAL,_Fields.STR_VAL,_Fields.BIN_VAL,_Fields.MAP_VAL,_Fields.LIST_VAL};
  public static final java.util.Map<_Fields, com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TYPE, new com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData("type", com.jetbrains.cef.remote.thrift.TFieldRequirementType.REQUIRED, 
        new com.jetbrains.cef.remote.thrift.meta_data.EnumMetaData(com.jetbrains.cef.remote.thrift.protocol.TType.ENUM, CefValueType.class)));
    tmpMap.put(_Fields.INT_VAL, new com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData("intVal", com.jetbrains.cef.remote.thrift.TFieldRequirementType.OPTIONAL, 
        new com.jetbrains.cef.remote.thrift.meta_data.FieldValueMetaData(com.jetbrains.cef.remote.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.DOUBLE_VAL, new com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData("doubleVal", com.jetbrains.cef.remote.thrift.TFieldRequirementType.OPTIONAL, 
        new com.jetbrains.cef.remote.thrift.meta_data.FieldValueMetaData(com.jetbrains.cef.remote.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.STR_VAL, new com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData("strVal", com.jetbrains.cef.remote.thrift.TFieldRequirementType.OPTIONAL, 
        new com.jetbrains.cef.remote.thrift.meta_data.FieldValueMetaData(com.jetbrains.cef.remote.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BIN_VAL, new com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData("binVal", com.jetbrains.cef.remote.thrift.TFieldRequirementType.OPTIONAL, 
        new com.jetbrains.cef.remote.thrift.meta_data.FieldValueMetaData(com.jetbrains.cef.remote.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.MAP_VAL, new com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData("mapVal", com.jetbrains.cef.remote.thrift.TFieldRequirementType.OPTIONAL, 
        new com.jetbrains.cef.remote.thrift.meta_data.MapMetaData(com.jetbrains.cef.remote.thrift.protocol.TType.MAP, 
            new com.jetbrains.cef.remote.thrift.meta_data.FieldValueMetaData(com.jetbrains.cef.remote.thrift.protocol.TType.STRING), 
            new com.jetbrains.cef.remote.thrift.meta_data.StructMetaData(com.jetbrains.cef.remote.thrift.protocol.TType.STRUCT, CefValue.class))));
    tmpMap.put(_Fields.LIST_VAL, new com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData("listVal", com.jetbrains.cef.remote.thrift.TFieldRequirementType.OPTIONAL, 
        new com.jetbrains.cef.remote.thrift.meta_data.ListMetaData(com.jetbrains.cef.remote.thrift.protocol.TType.LIST, 
            new com.jetbrains.cef.remote.thrift.meta_data.StructMetaData(com.jetbrains.cef.remote.thrift.protocol.TType.STRUCT, CefValue.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    com.jetbrains.cef.remote.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CefValue.class, metaDataMap);
  }

  public CefValue() {
    this.type = com.jetbrains.cef.remote.thrift_codegen.CefValueType.NONE;

  }

  public CefValue(
    CefValueType type)
  {
    this();
    this.type = type;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CefValue(CefValue other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetType()) {
      this.type = other.type;
    }
    this.intVal = other.intVal;
    this.doubleVal = other.doubleVal;
    if (other.isSetStrVal()) {
      this.strVal = other.strVal;
    }
    if (other.isSetBinVal()) {
      this.binVal = com.jetbrains.cef.remote.thrift.TBaseHelper.copyBinary(other.binVal);
    }
    if (other.isSetMapVal()) {
      java.util.Map<java.lang.String,CefValue> __this__mapVal = new java.util.HashMap<java.lang.String,CefValue>(other.mapVal.size());
      for (java.util.Map.Entry<java.lang.String, CefValue> other_element : other.mapVal.entrySet()) {

        java.lang.String other_element_key = other_element.getKey();
        CefValue other_element_value = other_element.getValue();

        java.lang.String __this__mapVal_copy_key = other_element_key;

        CefValue __this__mapVal_copy_value = new CefValue(other_element_value);

        __this__mapVal.put(__this__mapVal_copy_key, __this__mapVal_copy_value);
      }
      this.mapVal = __this__mapVal;
    }
    if (other.isSetListVal()) {
      java.util.List<CefValue> __this__listVal = new java.util.ArrayList<CefValue>(other.listVal.size());
      for (CefValue other_element : other.listVal) {
        __this__listVal.add(new CefValue(other_element));
      }
      this.listVal = __this__listVal;
    }
  }

  @Override
  public CefValue deepCopy() {
    return new CefValue(this);
  }

  @Override
  public void clear() {
    this.type = com.jetbrains.cef.remote.thrift_codegen.CefValueType.NONE;

    setIntValIsSet(false);
    this.intVal = 0;
    setDoubleValIsSet(false);
    this.doubleVal = 0.0;
    this.strVal = null;
    this.binVal = null;
    this.mapVal = null;
    this.listVal = null;
  }

  /**
   * 
   * @see CefValueType
   */
  @com.jetbrains.cef.remote.thrift.annotation.Nullable
  public CefValueType getType() {
    return this.type;
  }

  /**
   * 
   * @see CefValueType
   */
  public CefValue setType(@com.jetbrains.cef.remote.thrift.annotation.Nullable CefValueType type) {
    this.type = type;
    return this;
  }

  public void unsetType() {
    this.type = null;
  }

  /** Returns true if field type is set (has been assigned a value) and false otherwise */
  public boolean isSetType() {
    return this.type != null;
  }

  public void setTypeIsSet(boolean value) {
    if (!value) {
      this.type = null;
    }
  }

  public long getIntVal() {
    return this.intVal;
  }

  public CefValue setIntVal(long intVal) {
    this.intVal = intVal;
    setIntValIsSet(true);
    return this;
  }

  public void unsetIntVal() {
    __isset_bitfield = com.jetbrains.cef.remote.thrift.EncodingUtils.clearBit(__isset_bitfield, __INTVAL_ISSET_ID);
  }

  /** Returns true if field intVal is set (has been assigned a value) and false otherwise */
  public boolean isSetIntVal() {
    return com.jetbrains.cef.remote.thrift.EncodingUtils.testBit(__isset_bitfield, __INTVAL_ISSET_ID);
  }

  public void setIntValIsSet(boolean value) {
    __isset_bitfield = com.jetbrains.cef.remote.thrift.EncodingUtils.setBit(__isset_bitfield, __INTVAL_ISSET_ID, value);
  }

  public double getDoubleVal() {
    return this.doubleVal;
  }

  public CefValue setDoubleVal(double doubleVal) {
    this.doubleVal = doubleVal;
    setDoubleValIsSet(true);
    return this;
  }

  public void unsetDoubleVal() {
    __isset_bitfield = com.jetbrains.cef.remote.thrift.EncodingUtils.clearBit(__isset_bitfield, __DOUBLEVAL_ISSET_ID);
  }

  /** Returns true if field doubleVal is set (has been assigned a value) and false otherwise */
  public boolean isSetDoubleVal() {
    return com.jetbrains.cef.remote.thrift.EncodingUtils.testBit(__isset_bitfield, __DOUBLEVAL_ISSET_ID);
  }

  public void setDoubleValIsSet(boolean value) {
    __isset_bitfield = com.jetbrains.cef.remote.thrift.EncodingUtils.setBit(__isset_bitfield, __DOUBLEVAL_ISSET_ID, value);
  }

  @com.jetbrains.cef.remote.thrift.annotation.Nullable
  public java.lang.String getStrVal() {
    return this.strVal;
  }

  public CefValue setStrVal(@com.jetbrains.cef.remote.thrift.annotation.Nullable java.lang.String strVal) {
    this.strVal = strVal;
    return this;
  }

  public void unsetStrVal() {
    this.strVal = null;
  }

  /** Returns true if field strVal is set (has been assigned a value) and false otherwise */
  public boolean isSetStrVal() {
    return this.strVal != null;
  }

  public void setStrValIsSet(boolean value) {
    if (!value) {
      this.strVal = null;
    }
  }

  public byte[] getBinVal() {
    setBinVal(com.jetbrains.cef.remote.thrift.TBaseHelper.rightSize(binVal));
    return binVal == null ? null : binVal.array();
  }

  public java.nio.ByteBuffer bufferForBinVal() {
    return com.jetbrains.cef.remote.thrift.TBaseHelper.copyBinary(binVal);
  }

  public CefValue setBinVal(byte[] binVal) {
    this.binVal = binVal == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(binVal.clone());
    return this;
  }

  public CefValue setBinVal(@com.jetbrains.cef.remote.thrift.annotation.Nullable java.nio.ByteBuffer binVal) {
    this.binVal = com.jetbrains.cef.remote.thrift.TBaseHelper.copyBinary(binVal);
    return this;
  }

  public void unsetBinVal() {
    this.binVal = null;
  }

  /** Returns true if field binVal is set (has been assigned a value) and false otherwise */
  public boolean isSetBinVal() {
    return this.binVal != null;
  }

  public void setBinValIsSet(boolean value) {
    if (!value) {
      this.binVal = null;
    }
  }

  public int getMapValSize() {
    return (this.mapVal == null) ? 0 : this.mapVal.size();
  }

  public void putToMapVal(java.lang.String key, CefValue val) {
    if (this.mapVal == null) {
      this.mapVal = new java.util.HashMap<java.lang.String,CefValue>();
    }
    this.mapVal.put(key, val);
  }

  @com.jetbrains.cef.remote.thrift.annotation.Nullable
  public java.util.Map<java.lang.String,CefValue> getMapVal() {
    return this.mapVal;
  }

  public CefValue setMapVal(@com.jetbrains.cef.remote.thrift.annotation.Nullable java.util.Map<java.lang.String,CefValue> mapVal) {
    this.mapVal = mapVal;
    return this;
  }

  public void unsetMapVal() {
    this.mapVal = null;
  }

  /** Returns true if field mapVal is set (has been assigned a value) and false otherwise */
  public boolean isSetMapVal() {
    return this.mapVal != null;
  }

  public void setMapValIsSet(boolean value) {
    if (!value) {
      this.mapVal = null;
    }
  }

  public int getListValSize() {
    return (this.listVal == null) ? 0 : this.listVal.size();
  }

  @com.jetbrains.cef.remote.thrift.annotation.Nullable
  public java.util.Iterator<CefValue> getListValIterator() {
    return (this.listVal == null) ? null : this.listVal.iterator();
  }

  public void addToListVal(CefValue elem) {
    if (this.listVal == null) {
      this.listVal = new java.util.ArrayList<CefValue>();
    }
    this.listVal.add(elem);
  }

  @com.jetbrains.cef.remote.thrift.annotation.Nullable
  public java.util.List<CefValue> getListVal() {
    return this.listVal;
  }

  public CefValue setListVal(@com.jetbrains.cef.remote.thrift.annotation.Nullable java.util.List<CefValue> listVal) {
    this.listVal = listVal;
    return this;
  }

  public void unsetListVal() {
    this.listVal = null;
  }

  /** Returns true if field listVal is set (has been assigned a value) and false otherwise */
  public boolean isSetListVal() {
    return this.listVal != null;
  }

  public void setListValIsSet(boolean value) {
    if (!value) {
      this.listVal = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @com.jetbrains.cef.remote.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case TYPE:
      if (value == null) {
        unsetType();
      } else {
        setType((CefValueType)value);
      }
      break;

    case INT_VAL:
      if (value == null) {
        unsetIntVal();
      } else {
        setIntVal((java.lang.Long)value);
      }
      break;

    case DOUBLE_VAL:
      if (value == null) {
        unsetDoubleVal();
      } else {
        setDoubleVal((java.lang.Double)value);
      }
      break;

    case STR_VAL:
      if (value == null) {
        unsetStrVal();
      } else {
        setStrVal((java.lang.String)value);
      }
      break;

    case BIN_VAL:
      if (value == null) {
        unsetBinVal();
      } else {
        if (value instanceof byte[]) {
          setBinVal((byte[])value);
        } else {
          setBinVal((java.nio.ByteBuffer)value);
        }
      }
      break;

    case MAP_VAL:
      if (value == null) {
        unsetMapVal();
      } else {
        setMapVal((java.util.Map<java.lang.String,CefValue>)value);
      }
      break;

    case LIST_VAL:
      if (value == null) {
        unsetListVal();
      } else {
        setListVal((java.util.List<CefValue>)value);
      }
      break;

    }
  }

  @com.jetbrains.cef.remote.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TYPE:
      return getType();

    case INT_VAL:
      return getIntVal();

    case DOUBLE_VAL:
      return getDoubleVal();

    case STR_VAL:
      return getStrVal();

    case BIN_VAL:
      return getBinVal();

    case MAP_VAL:
      return getMapVal();

    case LIST_VAL:
      return getListVal();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TYPE:
      return isSetType();
    case INT_VAL:
      return isSetIntVal();
    case DOUBLE_VAL:
      return isSetDoubleVal();
    case STR_VAL:
      return isSetStrVal();
    case BIN_VAL:
      return isSetBinVal();
    case MAP_VAL:
      return isSetMapVal();
    case LIST_VAL:
      return isSetListVal();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof CefValue)
      return this.equals((CefValue)that);
    return false;
  }

  public boolean equals(CefValue that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_type = true && this.isSetType();
    boolean that_present_type = true && that.isSetType();
    if (this_present_type || that_present_type) {
      if (!(this_present_type && that_present_type))
        return false;
      if (!this.type.equals(that.type))
        return false;
    }

    boolean this_present_intVal = true && this.isSetIntVal();
    boolean that_present_intVal = true && that.isSetIntVal();
    if (this_present_intVal || that_present_intVal) {
      if (!(this_present_intVal && that_present_intVal))
        return false;
      if (this.intVal != that.intVal)
        return false;
    }

    boolean this_present_doubleVal = true && this.isSetDoubleVal();
    boolean that_present_doubleVal = true && that.isSetDoubleVal();
    if (this_present_doubleVal || that_present_doubleVal) {
      if (!(this_present_doubleVal && that_present_doubleVal))
        return false;
      if (this.doubleVal != that.doubleVal)
        return false;
    }

    boolean this_present_strVal = true && this.isSetStrVal();
    boolean that_present_strVal = true && that.isSetStrVal();
    if (this_present_strVal || that_present_strVal) {
      if (!(this_present_strVal && that_present_strVal))
        return false;
      if (!this.strVal.equals(that.strVal))
        return false;
    }

    boolean this_present_binVal = true && this.isSetBinVal();
    boolean that_present_binVal = true && that.isSetBinVal();
    if (this_present_binVal || that_present_binVal) {
      if (!(this_present_binVal && that_present_binVal))
        return false;
      if (!this.binVal.equals(that.binVal))
        return false;
    }

    boolean this_present_mapVal = true && this.isSetMapVal();
    boolean that_present_mapVal = true && that.isSetMapVal();
    if (this_present_mapVal || that_present_mapVal) {
      if (!(this_present_mapVal && that_present_mapVal))
        return false;
      if (!this.mapVal.equals(that.mapVal))
        return false;
    }

    boolean this_present_listVal = true && this.isSetListVal();
    boolean that_present_listVal = true && that.isSetListVal();
    if (this_present_listVal || that_present_listVal) {
      if (!(this_present_listVal && that_present_listVal))
        return false;
      if (!this.listVal.equals(that.listVal))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetType()) ? 131071 : 524287);
    if (isSetType())
      hashCode = hashCode * 8191 + type.getValue();

    hashCode = hashCode * 8191 + ((isSetIntVal()) ? 131071 : 524287);
    if (isSetIntVal())
      hashCode = hashCode * 8191 + com.jetbrains.cef.remote.thrift.TBaseHelper.hashCode(intVal);

    hashCode = hashCode * 8191 + ((isSetDoubleVal()) ? 131071 : 524287);
    if (isSetDoubleVal())
      hashCode = hashCode * 8191 + com.jetbrains.cef.remote.thrift.TBaseHelper.hashCode(doubleVal);

    hashCode = hashCode * 8191 + ((isSetStrVal()) ? 131071 : 524287);
    if (isSetStrVal())
      hashCode = hashCode * 8191 + strVal.hashCode();

    hashCode = hashCode * 8191 + ((isSetBinVal()) ? 131071 : 524287);
    if (isSetBinVal())
      hashCode = hashCode * 8191 + binVal.hashCode();

    hashCode = hashCode * 8191 + ((isSetMapVal()) ? 131071 : 524287);
    if (isSetMapVal())
      hashCode = hashCode * 8191 + mapVal.hashCode();

    hashCode = hashCode * 8191 + ((isSetListVal()) ? 131071 : 524287);
    if (isSetListVal())
      hashCode = hashCode * 8191 + listVal.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(CefValue other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetType(), other.isSetType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType()) {
      lastComparison = com.jetbrains.cef.remote.thrift.TBaseHelper.compareTo(this.type, other.type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetIntVal(), other.isSetIntVal());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIntVal()) {
      lastComparison = com.jetbrains.cef.remote.thrift.TBaseHelper.compareTo(this.intVal, other.intVal);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDoubleVal(), other.isSetDoubleVal());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDoubleVal()) {
      lastComparison = com.jetbrains.cef.remote.thrift.TBaseHelper.compareTo(this.doubleVal, other.doubleVal);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetStrVal(), other.isSetStrVal());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStrVal()) {
      lastComparison = com.jetbrains.cef.remote.thrift.TBaseHelper.compareTo(this.strVal, other.strVal);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetBinVal(), other.isSetBinVal());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBinVal()) {
      lastComparison = com.jetbrains.cef.remote.thrift.TBaseHelper.compareTo(this.binVal, other.binVal);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMapVal(), other.isSetMapVal());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMapVal()) {
      lastComparison = com.jetbrains.cef.remote.thrift.TBaseHelper.compareTo(this.mapVal, other.mapVal);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetListVal(), other.isSetListVal());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetListVal()) {
      lastComparison = com.jetbrains.cef.remote.thrift.TBaseHelper.compareTo(this.listVal, other.listVal);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @com.jetbrains.cef.remote.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(com.jetbrains.cef.remote.thrift.protocol.TProtocol iprot) throws com.jetbrains.cef.remote.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(com.jetbrains.cef.remote.thrift.protocol.TProtocol oprot) throws com.jetbrains.cef.remote.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("CefValue(");
    boolean first = true;

    sb.append("type:");
    if (this.type == null) {
      sb.append("null");
    } else {
      sb.append(this.type);
    }
    first = false;
    if (isSetIntVal()) {
      if (!first) sb.append(", ");
      sb.append("intVal:");
      sb.append(this.intVal);
      first = false;
    }
    if (isSetDoubleVal()) {
      if (!first) sb.append(", ");
      sb.append("doubleVal:");
      sb.append(this.doubleVal);
      first = false;
    }
    if (isSetStrVal()) {
      if (!first) sb.append(", ");
      sb.append("strVal:");
      if (this.strVal == null) {
        sb.append("null");
      } else {
        sb.append(this.strVal);
      }
      first = false;
    }
    if (isSetBinVal()) {
      if (!first) sb.append(", ");
      sb.append("binVal:");
      if (this.binVal == null) {
        sb.append("null");
      } else {
        com.jetbrains.cef.remote.thrift.TBaseHelper.toString(this.binVal, sb);
      }
      first = false;
    }
    if (isSetMapVal()) {
      if (!first) sb.append(", ");
      sb.append("mapVal:");
      if (this.mapVal == null) {
        sb.append("null");
      } else {
        sb.append(this.mapVal);
      }
      first = false;
    }
    if (isSetListVal()) {
      if (!first) sb.append(", ");
      sb.append("listVal:");
      if (this.listVal == null) {
        sb.append("null");
      } else {
        sb.append(this.listVal);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws com.jetbrains.cef.remote.thrift.TException {
    // check for required fields
    if (type == null) {
      throw new com.jetbrains.cef.remote.thrift.protocol.TProtocolException("Required field 'type' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new com.jetbrains.cef.remote.thrift.protocol.TCompactProtocol(new com.jetbrains.cef.remote.thrift.transport.TIOStreamTransport(out)));
    } catch (com.jetbrains.cef.remote.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new com.jetbrains.cef.remote.thrift.protocol.TCompactProtocol(new com.jetbrains.cef.remote.thrift.transport.TIOStreamTransport(in)));
    } catch (com.jetbrains.cef.remote.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CefValueStandardSchemeFactory implements com.jetbrains.cef.remote.thrift.scheme.SchemeFactory {
    @Override
    public CefValueStandardScheme getScheme() {
      return new CefValueStandardScheme();
    }
  }

  private static class CefValueStandardScheme extends com.jetbrains.cef.remote.thrift.scheme.StandardScheme<CefValue> {

    @Override
    public void read(com.jetbrains.cef.remote.thrift.protocol.TProtocol iprot, CefValue struct) throws com.jetbrains.cef.remote.thrift.TException {
      com.jetbrains.cef.remote.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == com.jetbrains.cef.remote.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TYPE
            if (schemeField.type == com.jetbrains.cef.remote.thrift.protocol.TType.I32) {
              struct.type = com.jetbrains.cef.remote.thrift_codegen.CefValueType.findByValue(iprot.readI32());
              struct.setTypeIsSet(true);
            } else { 
              com.jetbrains.cef.remote.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // INT_VAL
            if (schemeField.type == com.jetbrains.cef.remote.thrift.protocol.TType.I64) {
              struct.intVal = iprot.readI64();
              struct.setIntValIsSet(true);
            } else { 
              com.jetbrains.cef.remote.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DOUBLE_VAL
            if (schemeField.type == com.jetbrains.cef.remote.thrift.protocol.TType.DOUBLE) {
              struct.doubleVal = iprot.readDouble();
              struct.setDoubleValIsSet(true);
            } else { 
              com.jetbrains.cef.remote.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // STR_VAL
            if (schemeField.type == com.jetbrains.cef.remote.thrift.protocol.TType.STRING) {
              struct.strVal = iprot.readString();
              struct.setStrValIsSet(true);
            } else { 
              com.jetbrains.cef.remote.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // BIN_VAL
            if (schemeField.type == com.jetbrains.cef.remote.thrift.protocol.TType.STRING) {
              struct.binVal = iprot.readBinary();
              struct.setBinValIsSet(true);
            } else { 
              com.jetbrains.cef.remote.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // MAP_VAL
            if (schemeField.type == com.jetbrains.cef.remote.thrift.protocol.TType.MAP) {
              {
                com.jetbrains.cef.remote.thrift.protocol.TMap _map18 = iprot.readMapBegin();
                struct.mapVal = new java.util.HashMap<java.lang.String,CefValue>(2*_map18.size);
                @com.jetbrains.cef.remote.thrift.annotation.Nullable java.lang.String _key19;
                @com.jetbrains.cef.remote.thrift.annotation.Nullable CefValue _val20;
                for (int _i21 = 0; _i21 < _map18.size; ++_i21)
                {
                  _key19 = iprot.readString();
                  _val20 = new CefValue();
                  _val20.read(iprot);
                  struct.mapVal.put(_key19, _val20);
                }
                iprot.readMapEnd();
              }
              struct.setMapValIsSet(true);
            } else { 
              com.jetbrains.cef.remote.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // LIST_VAL
            if (schemeField.type == com.jetbrains.cef.remote.thrift.protocol.TType.LIST) {
              {
                com.jetbrains.cef.remote.thrift.protocol.TList _list22 = iprot.readListBegin();
                struct.listVal = new java.util.ArrayList<CefValue>(_list22.size);
                @com.jetbrains.cef.remote.thrift.annotation.Nullable CefValue _elem23;
                for (int _i24 = 0; _i24 < _list22.size; ++_i24)
                {
                  _elem23 = new CefValue();
                  _elem23.read(iprot);
                  struct.listVal.add(_elem23);
                }
                iprot.readListEnd();
              }
              struct.setListValIsSet(true);
            } else { 
              com.jetbrains.cef.remote.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            com.jetbrains.cef.remote.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(com.jetbrains.cef.remote.thrift.protocol.TProtocol oprot, CefValue struct) throws com.jetbrains.cef.remote.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.type != null) {
        oprot.writeFieldBegin(TYPE_FIELD_DESC);
        oprot.writeI32(struct.type.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.isSetIntVal()) {
        oprot.writeFieldBegin(INT_VAL_FIELD_DESC);
        oprot.writeI64(struct.intVal);
        oprot.writeFieldEnd();
      }
      if (struct.isSetDoubleVal()) {
        oprot.writeFieldBegin(DOUBLE_VAL_FIELD_DESC);
        oprot.writeDouble(struct.doubleVal);
        oprot.writeFieldEnd();
      }
      if (struct.strVal != null) {
        if (struct.isSetStrVal()) {
          oprot.writeFieldBegin(STR_VAL_FIELD_DESC);
          oprot.writeString(struct.strVal);
          oprot.writeFieldEnd();
        }
      }
      if (struct.binVal != null) {
        if (struct.isSetBinVal()) {
          oprot.writeFieldBegin(BIN_VAL_FIELD_DESC);
          oprot.writeBinary(struct.binVal);
          oprot.writeFieldEnd();
        }
      }
      if (struct.mapVal != null) {
        if (struct.isSetMapVal()) {
          oprot.writeFieldBegin(MAP_VAL_FIELD_DESC);
          {
            oprot.writeMapBegin(new com.jetbrains.cef.remote.thrift.protocol.TMap(com.jetbrains.cef.remote.thrift.protocol.TType.STRING, com.jetbrains.cef.remote.thrift.protocol.TType.STRUCT, struct.mapVal.size()));
            for (java.util.Map.Entry<java.lang.String, CefValue> _iter25 : struct.mapVal.entrySet())
            {
              oprot.writeString(_iter25.getKey());
              _iter25.getValue().write(oprot);
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.listVal != null) {
        if (struct.isSetListVal()) {
          oprot.writeFieldBegin(LIST_VAL_FIELD_DESC);
          {
            oprot.writeListBegin(new com.jetbrains.cef.remote.thrift.protocol.TList(com.jetbrains.cef.remote.thrift.protocol.TType.STRUCT, struct.listVal.size()));
            for (CefValue _iter26 : struct.listVal)
            {
              _iter26.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CefValueTupleSchemeFactory implements com.jetbrains.cef.remote.thrift.scheme.SchemeFactory {
    @Override
    public CefValueTupleScheme getScheme() {
      return new CefValueTupleScheme();
    }
  }

  private static class CefValueTupleScheme extends com.jetbrains.cef.remote.thrift.scheme.TupleScheme<CefValue> {

    @Override
    public void write(com.jetbrains.cef.remote.thrift.protocol.TProtocol prot, CefValue struct) throws com.jetbrains.cef.remote.thrift.TException {
      com.jetbrains.cef.remote.thrift.protocol.TTupleProtocol oprot = (com.jetbrains.cef.remote.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.type.getValue());
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetIntVal()) {
        optionals.set(0);
      }
      if (struct.isSetDoubleVal()) {
        optionals.set(1);
      }
      if (struct.isSetStrVal()) {
        optionals.set(2);
      }
      if (struct.isSetBinVal()) {
        optionals.set(3);
      }
      if (struct.isSetMapVal()) {
        optionals.set(4);
      }
      if (struct.isSetListVal()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetIntVal()) {
        oprot.writeI64(struct.intVal);
      }
      if (struct.isSetDoubleVal()) {
        oprot.writeDouble(struct.doubleVal);
      }
      if (struct.isSetStrVal()) {
        oprot.writeString(struct.strVal);
      }
      if (struct.isSetBinVal()) {
        oprot.writeBinary(struct.binVal);
      }
      if (struct.isSetMapVal()) {
        {
          oprot.writeI32(struct.mapVal.size());
          for (java.util.Map.Entry<java.lang.String, CefValue> _iter27 : struct.mapVal.entrySet())
          {
            oprot.writeString(_iter27.getKey());
            _iter27.getValue().write(oprot);
          }
        }
      }
      if (struct.isSetListVal()) {
        {
          oprot.writeI32(struct.listVal.size());
          for (CefValue _iter28 : struct.listVal)
          {
            _iter28.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(com.jetbrains.cef.remote.thrift.protocol.TProtocol prot, CefValue struct) throws com.jetbrains.cef.remote.thrift.TException {
      com.jetbrains.cef.remote.thrift.protocol.TTupleProtocol iprot = (com.jetbrains.cef.remote.thrift.protocol.TTupleProtocol) prot;
      struct.type = com.jetbrains.cef.remote.thrift_codegen.CefValueType.findByValue(iprot.readI32());
      struct.setTypeIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.intVal = iprot.readI64();
        struct.setIntValIsSet(true);
      }
      if (incoming.get(1)) {
        struct.doubleVal = iprot.readDouble();
        struct.setDoubleValIsSet(true);
      }
      if (incoming.get(2)) {
        struct.strVal = iprot.readString();
        struct.setStrValIsSet(true);
      }
      if (incoming.get(3)) {
        struct.binVal = iprot.readBinary();
        struct.setBinValIsSet(true);
      }
      if (incoming.get(4)) {
        {
          com.jetbrains.cef.remote.thrift.protocol.TMap _map29 = iprot.readMapBegin(com.jetbrains.cef.remote.thrift.protocol.TType.STRING, com.jetbrains.cef.remote.thrift.protocol.TType.STRUCT); 
          struct.mapVal = new java.util.HashMap<java.lang.String,CefValue>(2*_map29.size);
          @com.jetbrains.cef.remote.thrift.annotation.Nullable java.lang.String _key30;
          @com.jetbrains.cef.remote.thrift.annotation.Nullable CefValue _val31;
          for (int _i32 = 0; _i32 < _map29.size; ++_i32)
          {
            _key30 = iprot.readString();
            _val31 = new CefValue();
            _val31.read(iprot);
            struct.mapVal.put(_key30, _val31);
          }
        }
        struct.setMapValIsSet(true);
      }
      if (incoming.get(5)) {
        {
          com.jetbrains.cef.remote.thrift.protocol.TList _list33 = iprot.readListBegin(com.jetbrains.cef.remote.thrift.protocol.TType.STRUCT);
          struct.listVal = new java.util.ArrayList<CefValue>(_list33.size);
          @com.jetbrains.cef.remote.thrift.annotation.Nullable CefValue _elem34;
          for (int _i35 = 0; _i35 < _list33.size; ++_i35)
          {
            _elem34 = new CefValue();
            _elem34.read(iprot);
            struct.listVal.add(_elem34);
          }
        }
        struct.setListValIsSet(true);
      }
    }
  }

  private static <S extends com.jetbrains.cef.remote.thrift.scheme.IScheme> S scheme(com.jetbrains.cef.remote.thrift.protocol.TProtocol proto) {
    return (com.jetbrains.cef.remote.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

