/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.jetbrains.cef.remote.thrift_codegen;


public enum Style implements com.jetbrains.cef.remote.thrift.TEnum {
  SOLID(0),
  DOT(1),
  DASH(2),
  NONE(3);

  private final int value;

  private Style(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @com.jetbrains.cef.remote.thrift.annotation.Nullable
  public static Style findByValue(int value) { 
    switch (value) {
      case 0:
        return SOLID;
      case 1:
        return DOT;
      case 2:
        return DASH;
      case 3:
        return NONE;
      default:
        return null;
    }
  }
}
