/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef shared_TYPES_H
#define shared_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace thrift_codegen {

struct Style {
  enum type {
    SOLID = 0,
    DOT = 1,
    DASH = 2,
    NONE = 3
  };
};

extern const std::map<int, const char*> _Style_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const Style::type& val);

std::string to_string(const Style::type& val);

struct CefValueType {
  enum type {
    BOOL = 0,
    INT = 1,
    DOUBLE = 2,
    STRING = 3,
    BYTE_BUFFER = 4,
    MAP = 5,
    LIST = 6,
    NONE = 7
  };
};

extern const std::map<int, const char*> _CefValueType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const CefValueType::type& val);

std::string to_string(const CefValueType::type& val);

class RObject;

class ResponseHeaders;

class ResponseData;

class PostDataElement;

class PostData;

class KeyEvent;

class Cookie;

class Range;

class Color;

class CompositionUnderline;

class CefValue;

typedef struct _RObject__isset {
  _RObject__isset() : flags(false), info(false) {}
  bool flags :1;
  bool info :1;
} _RObject__isset;

class RObject : public virtual ::apache::thrift::TBase {
 public:

  RObject(const RObject&);
  RObject& operator=(const RObject&);
  RObject() noexcept;

  virtual ~RObject() noexcept;
  bool isNull;
  int32_t uid;
  int32_t flags;
  std::map<std::string, std::string>  info;

  _RObject__isset __isset;

  void __set_isNull(const bool val);

  void __set_uid(const int32_t val);

  void __set_flags(const int32_t val);

  void __set_info(const std::map<std::string, std::string> & val);

  bool operator == (const RObject & rhs) const;
  bool operator != (const RObject &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RObject & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(RObject &a, RObject &b) noexcept;

std::ostream& operator<<(std::ostream& out, const RObject& obj);

typedef struct _ResponseHeaders__isset {
  _ResponseHeaders__isset() : redirectUrl(false) {}
  bool redirectUrl :1;
} _ResponseHeaders__isset;

class ResponseHeaders : public virtual ::apache::thrift::TBase {
 public:

  ResponseHeaders(const ResponseHeaders&);
  ResponseHeaders& operator=(const ResponseHeaders&);
  ResponseHeaders() noexcept;

  virtual ~ResponseHeaders() noexcept;
  int32_t length;
  std::string redirectUrl;

  _ResponseHeaders__isset __isset;

  void __set_length(const int32_t val);

  void __set_redirectUrl(const std::string& val);

  bool operator == (const ResponseHeaders & rhs) const;
  bool operator != (const ResponseHeaders &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ResponseHeaders & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ResponseHeaders &a, ResponseHeaders &b) noexcept;

std::ostream& operator<<(std::ostream& out, const ResponseHeaders& obj);

typedef struct _ResponseData__isset {
  _ResponseData__isset() : continueRead(false), data(false), bytes_read(false) {}
  bool continueRead :1;
  bool data :1;
  bool bytes_read :1;
} _ResponseData__isset;

class ResponseData : public virtual ::apache::thrift::TBase {
 public:

  ResponseData(const ResponseData&);
  ResponseData& operator=(const ResponseData&);
  ResponseData() noexcept;

  virtual ~ResponseData() noexcept;
  bool continueRead;
  std::string data;
  int32_t bytes_read;

  _ResponseData__isset __isset;

  void __set_continueRead(const bool val);

  void __set_data(const std::string& val);

  void __set_bytes_read(const int32_t val);

  bool operator == (const ResponseData & rhs) const;
  bool operator != (const ResponseData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ResponseData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ResponseData &a, ResponseData &b) noexcept;

std::ostream& operator<<(std::ostream& out, const ResponseData& obj);

typedef struct _PostDataElement__isset {
  _PostDataElement__isset() : file(false), bytes(false) {}
  bool file :1;
  bool bytes :1;
} _PostDataElement__isset;

class PostDataElement : public virtual ::apache::thrift::TBase {
 public:

  PostDataElement(const PostDataElement&);
  PostDataElement& operator=(const PostDataElement&);
  PostDataElement() noexcept;

  virtual ~PostDataElement() noexcept;
  bool isReadOnly;
  int32_t type;
  std::string file;
  std::string bytes;

  _PostDataElement__isset __isset;

  void __set_isReadOnly(const bool val);

  void __set_type(const int32_t val);

  void __set_file(const std::string& val);

  void __set_bytes(const std::string& val);

  bool operator == (const PostDataElement & rhs) const;
  bool operator != (const PostDataElement &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PostDataElement & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(PostDataElement &a, PostDataElement &b) noexcept;

std::ostream& operator<<(std::ostream& out, const PostDataElement& obj);

typedef struct _PostData__isset {
  _PostData__isset() : elements(false) {}
  bool elements :1;
} _PostData__isset;

class PostData : public virtual ::apache::thrift::TBase {
 public:

  PostData(const PostData&);
  PostData& operator=(const PostData&);
  PostData() noexcept;

  virtual ~PostData() noexcept;
  bool isNull;
  bool isReadOnly;
  bool hasExcludedElements;
  std::vector<PostDataElement>  elements;

  _PostData__isset __isset;

  void __set_isNull(const bool val);

  void __set_isReadOnly(const bool val);

  void __set_hasExcludedElements(const bool val);

  void __set_elements(const std::vector<PostDataElement> & val);

  bool operator == (const PostData & rhs) const;
  bool operator != (const PostData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PostData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(PostData &a, PostData &b) noexcept;

std::ostream& operator<<(std::ostream& out, const PostData& obj);


class KeyEvent : public virtual ::apache::thrift::TBase {
 public:

  KeyEvent(const KeyEvent&);
  KeyEvent& operator=(const KeyEvent&);
  KeyEvent() noexcept;

  virtual ~KeyEvent() noexcept;
  std::string type;
  int32_t modifiers;
  int32_t windows_key_code;
  int32_t native_key_code;
  bool is_system_key;
  int16_t character;
  int16_t unmodified_character;
  bool focus_on_editable_field;

  void __set_type(const std::string& val);

  void __set_modifiers(const int32_t val);

  void __set_windows_key_code(const int32_t val);

  void __set_native_key_code(const int32_t val);

  void __set_is_system_key(const bool val);

  void __set_character(const int16_t val);

  void __set_unmodified_character(const int16_t val);

  void __set_focus_on_editable_field(const bool val);

  bool operator == (const KeyEvent & rhs) const;
  bool operator != (const KeyEvent &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KeyEvent & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(KeyEvent &a, KeyEvent &b) noexcept;

std::ostream& operator<<(std::ostream& out, const KeyEvent& obj);

typedef struct _Cookie__isset {
  _Cookie__isset() : expires(false) {}
  bool expires :1;
} _Cookie__isset;

class Cookie : public virtual ::apache::thrift::TBase {
 public:

  Cookie(const Cookie&);
  Cookie& operator=(const Cookie&);
  Cookie() noexcept;

  virtual ~Cookie() noexcept;
  std::string name;
  std::string value;
  std::string domain;
  std::string path;
  bool secure;
  bool httponly;
  int64_t creation;
  int64_t lastAccess;
  int64_t expires;

  _Cookie__isset __isset;

  void __set_name(const std::string& val);

  void __set_value(const std::string& val);

  void __set_domain(const std::string& val);

  void __set_path(const std::string& val);

  void __set_secure(const bool val);

  void __set_httponly(const bool val);

  void __set_creation(const int64_t val);

  void __set_lastAccess(const int64_t val);

  void __set_expires(const int64_t val);

  bool operator == (const Cookie & rhs) const;
  bool operator != (const Cookie &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Cookie & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(Cookie &a, Cookie &b) noexcept;

std::ostream& operator<<(std::ostream& out, const Cookie& obj);


class Range : public virtual ::apache::thrift::TBase {
 public:

  Range(const Range&) noexcept;
  Range& operator=(const Range&) noexcept;
  Range() noexcept;

  virtual ~Range() noexcept;
  int64_t from;
  int64_t to;

  void __set_from(const int64_t val);

  void __set_to(const int64_t val);

  bool operator == (const Range & rhs) const;
  bool operator != (const Range &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Range & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(Range &a, Range &b) noexcept;

std::ostream& operator<<(std::ostream& out, const Range& obj);

typedef struct _Color__isset {
  _Color__isset() : red(false), green(false), blue(false), alpha(false) {}
  bool red :1;
  bool green :1;
  bool blue :1;
  bool alpha :1;
} _Color__isset;

class Color : public virtual ::apache::thrift::TBase {
 public:

  Color(const Color&) noexcept;
  Color& operator=(const Color&) noexcept;
  Color() noexcept;

  virtual ~Color() noexcept;
  int32_t red;
  int32_t green;
  int32_t blue;
  int32_t alpha;

  _Color__isset __isset;

  void __set_red(const int32_t val);

  void __set_green(const int32_t val);

  void __set_blue(const int32_t val);

  void __set_alpha(const int32_t val);

  bool operator == (const Color & rhs) const;
  bool operator != (const Color &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Color & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(Color &a, Color &b) noexcept;

std::ostream& operator<<(std::ostream& out, const Color& obj);


class CompositionUnderline : public virtual ::apache::thrift::TBase {
 public:

  CompositionUnderline(const CompositionUnderline&) noexcept;
  CompositionUnderline& operator=(const CompositionUnderline&) noexcept;
  CompositionUnderline() noexcept;

  virtual ~CompositionUnderline() noexcept;
  Range range;
  Color color;
  Color backgroundColor;
  int32_t thick;
  /**
   * 
   * @see Style
   */
  Style::type style;

  void __set_range(const Range& val);

  void __set_color(const Color& val);

  void __set_backgroundColor(const Color& val);

  void __set_thick(const int32_t val);

  void __set_style(const Style::type val);

  bool operator == (const CompositionUnderline & rhs) const;
  bool operator != (const CompositionUnderline &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CompositionUnderline & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(CompositionUnderline &a, CompositionUnderline &b) noexcept;

std::ostream& operator<<(std::ostream& out, const CompositionUnderline& obj);

typedef struct _CefValue__isset {
  _CefValue__isset() : intVal(false), doubleVal(false), strVal(false), binVal(false), mapVal(false), listVal(false) {}
  bool intVal :1;
  bool doubleVal :1;
  bool strVal :1;
  bool binVal :1;
  bool mapVal :1;
  bool listVal :1;
} _CefValue__isset;

class CefValue : public virtual ::apache::thrift::TBase {
 public:

  CefValue(const CefValue&);
  CefValue& operator=(const CefValue&);
  CefValue() noexcept;

  virtual ~CefValue() noexcept;
  /**
   * 
   * @see CefValueType
   */
  CefValueType::type type;
  int64_t intVal;
  double doubleVal;
  std::string strVal;
  std::string binVal;
  std::map<std::string, CefValue>  mapVal;
  std::vector<CefValue>  listVal;

  _CefValue__isset __isset;

  void __set_type(const CefValueType::type val);

  void __set_intVal(const int64_t val);

  void __set_doubleVal(const double val);

  void __set_strVal(const std::string& val);

  void __set_binVal(const std::string& val);

  void __set_mapVal(const std::map<std::string, CefValue> & val);

  void __set_listVal(const std::vector<CefValue> & val);

  bool operator == (const CefValue & rhs) const;
  bool operator != (const CefValue &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CefValue & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(CefValue &a, CefValue &b) noexcept;

std::ostream& operator<<(std::ostream& out, const CefValue& obj);

} // namespace

#endif
