set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CXX_FLAGS "/D _ITERATOR_DEBUG_LEVEL=0")
set(VCPKG_C_FLAGS "/D _ITERATOR_DEBUG_LEVEL=0")
