FROM arm64v8/ubuntu:20.04

# Install the necessary build tools
ARG DEBIAN_FRONTEND=noninteractive
ARG DEBCONF_NONINTERACTIVE_SEEN=true 

RUN apt-get update && \
    echo 'tzdata tzdata/Areas select Etc' | debconf-set-selections && \
    echo 'tzdata tzdata/Zones/Etc select UTC' | debconf-set-selections && \
    apt-get install -y \
        ant=1.10.7-1 \
        libgbm-dev=21.2.6-0ubuntu0.1~20.04.2 \
        libxkbcommon-x11-dev=0.10.0-1 \
        bison=2:3.5.1+dfsg-1 \
        build-essential=12.8ubuntu1.1 \
        curl=7.68.0-1ubuntu2.23 \
        ninja-build=1.10.0-1build1 \
        flex=2.6.4-6.2 \
        git=1:2.25.1-1ubuntu3.13 \
        openjdk-17-jdk \
        pkg-config=0.29.1-0ubuntu4 \
        python3=3.8.2-0ubuntu2 \
        tar=1.30+dfsg-7ubuntu0.20.04.4 \
        unzip=6.0-25ubuntu1.2 \
        zip=3.0-11build1

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-arm64/        

ARG CMAKE_VERIONS=3.30.3
RUN curl -sSL https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERIONS}/cmake-${CMAKE_VERIONS}-linux-aarch64.tar.gz | tar -xz -C /opt/ && \
    ln -s /opt/cmake-${CMAKE_VERIONS}-linux-aarch64/bin/cmake /usr/local/bin/cmake && \
    ln -s /opt/cmake-${CMAKE_VERIONS}-linux-aarch64/bin/ctest /usr/local/bin/ctest && \
    cmake --version

RUN echo 'cd /mnt/home/develop/jcef_master_linux && sh ./build.sh' > /go.sh;
