/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefRunContextMenuCallback_N */

#ifndef _Included_org_cef_callback_CefRunContextMenuCallback_N
#define _Included_org_cef_callback_CefRunContextMenuCallback_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefRunContextMenuCallback_N
 * Method:    N_Continue
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_cef_callback_CefRunContextMenuCallback_1N_N_1Continue
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_cef_callback_CefRunContextMenuCallback_N
 * Method:    N_Cancel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cef_callback_CefRunContextMenuCallback_1N_N_1Cancel
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
